apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vector-db
  labels:
    app: {{ .Release.Name }}-vector-db
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-vector-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-vector-db
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

