"""add metadata to chunk

Revision ID: a640fc59dfb1
Revises: 097ef6a16cb6
Create Date: 2024-08-16 23:33:32.655522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a640fc59dfb1'
down_revision: Union[str, None] = '097ef6a16cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'chunk_metadata')
    # ### end Alembic commands ###
