apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "vector-db-chart.fullname" . } }
  labels:
    app: { { include "vector-db-chart.name" . } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { include "vector-db-chart.name" . } }
  template:
    metadata:
      labels:
        app: { { include "vector-db-chart.name" . } }
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
